version: "3"

services:
  php:
    build: docker
    volumes:
      - $PWD:/app
    working_dir: /app
    ports:
      - "8080:80"
  database:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=drupal8
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - $PWD:/app

volumes:
  database: